In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


In [2]:
if torch.cuda.is_available():
  print("gpu is available")
  print(f"using gpu {torch.cuda.get_device_name(0)}")
else:
  print("gpu not available using cpu")

gpu is available
using gpu Tesla T4


In [4]:
# creating a tensor
a = torch.empty(2 , 3)
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.1406, 0.8298, 0.2782],
        [0.0718, 0.7507, 0.8460]])

In [8]:
# use of seed - maintains same set of values for rand
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# arange
print(torch.arange(0,10,2))

tensor([0, 2, 4, 6, 8])


In [12]:
# linspace - evenly spaced values
print(torch.linspace(0,10,10))

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [13]:
# eye - identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
# full
torch.full((3,3) , 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [15]:
# tensor shapes

x = torch.tensor([[1,2,3],[4,5,6]])
a.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[          543688208,           543034704,                  80],
        [                 64,           545729389, 3344032066469896736]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x , dtype=torch.float32)
# wont work without specifying dtype as our x contains integers but rand generates floats

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [20]:
# data types
x.dtype

torch.int64

In [21]:
# assign data type
torch.tensor([1.0,2.0,3.0] , dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3] , dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
# using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [25]:
# math op

x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [26]:
# add
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [27]:
# subtraction
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [28]:
# multiplication
x * 2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [29]:
# division
x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [30]:
# int div
(x * 100) // 3

tensor([[23., 26.],
        [13., 30.]])

In [31]:
# mod
((x * 100) // 3) % 2

tensor([[1., 0.],
        [1., 0.]])

In [32]:
# power
x ** 2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [39]:
# element wise op

a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])
tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])


In [40]:
# add , sub, mul , div
a+b
a-b
a*b
a/b
a ** b
a % b

tensor([[0.0250, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [41]:
c = torch.tensor([1 , -2 , 3 , -4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [42]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [43]:
d = torch.tensor([1.9 , 2.3 , 4.5 , 3.4])
torch.round(d)

tensor([2., 2., 4., 3.])

In [45]:
# ceil and floor
torch.ceil(d)
torch.floor(d)

tensor([1., 2., 4., 3.])

In [47]:
# clamp adjusts values between min and max
torch.clamp(d , min =2 , max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [54]:
e = torch.randint(size=(2,3) , low = 0 , high = 10 , dtype=torch.float64)
e

tensor([[6., 1., 5.],
        [5., 0., 4.]], dtype=torch.float64)

In [55]:
# sum
torch.sum(e)

tensor(21., dtype=torch.float64)

In [56]:
# sum along cols
torch.sum(e , dim=0)

tensor([11.,  1.,  9.], dtype=torch.float64)

In [57]:
# sum along rows
torch.sum(e , dim=1)

tensor([12.,  9.], dtype=torch.float64)

In [59]:
# mean
torch.mean(e)
torch.mean(e , dim = 0)
torch.mean(e , dim = 1)

tensor([4., 3.], dtype=torch.float64)

In [60]:
# median
torch.median(e)
torch.median(e , dim = 0)
torch.median(e , dim = 1)

torch.return_types.median(
values=tensor([5., 4.], dtype=torch.float64),
indices=tensor([2, 2]))

In [62]:
# max and min
torch.max(e)
torch.min(e)

tensor(0., dtype=torch.float64)

In [63]:
# product
torch.prod(e)

tensor(0., dtype=torch.float64)

In [64]:
# std deviation
torch.std(e)

tensor(2.4290, dtype=torch.float64)

In [65]:
# variance
torch.var(e)

tensor(5.9000, dtype=torch.float64)

In [67]:
# argmax - postiion of max elemment in the tensoor
torch.argmax(e)

tensor(0)

In [69]:
# argmin - pos of min element iin tensor
torch.argmin(e)

tensor(4)

In [72]:
# matrix operations
f = torch.randint(size=(2,3) , low=0, high=10)
g = torch.randint(size=(3,2) , low=0, high=10)

print(f)
print(g)

tensor([[7, 1, 1],
        [5, 4, 4]])
tensor([[1, 1],
        [2, 4],
        [7, 2]])


In [73]:
# matrix mult
torch.matmul(f,g)

tensor([[16, 13],
        [41, 29]])

In [74]:
# vector dot prod
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1,vector2)

tensor(11)

In [75]:
# transpose
torch.transpose(f , 0 , 1)

tensor([[7, 5],
        [1, 4],
        [1, 4]])

In [79]:
# determinant
h = torch.randint(size=(3,3) , low = 0 , high = 10 , dtype=torch.float32)
torch.det(h)

tensor(-38.)

In [81]:
# inverse
torch.inverse(h)

tensor([[ 0.1579, -0.1053,  0.1053],
        [-1.5526,  0.3684,  0.1316],
        [ 0.4211,  0.0526, -0.0526]])

In [91]:
# comparison operations
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10 , dtype=torch.float32)

print(i)
print(j)

tensor([[4, 4, 6],
        [2, 1, 0]])
tensor([[5., 1., 0.],
        [0., 2., 2.]])


In [84]:
print(i > j )

print(i < j)

print(i == j)

print(i != j)


tensor([[False, False,  True],
        [False,  True, False]])
tensor([[ True,  True, False],
        [ True, False,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


In [86]:
# log
torch.log(j)

tensor([[1.9459, 2.1972, 0.6931],
        [1.9459,   -inf, 0.6931]])

In [87]:
# exp
torch.exp(j)

tensor([[1.0966e+03, 8.1031e+03, 7.3891e+00],
        [1.0966e+03, 1.0000e+00, 7.3891e+00]])

In [89]:
# sqrt
torch.sqrt(j)

tensor([[2.6458, 3.0000, 1.4142],
        [2.6458, 0.0000, 1.4142]])

In [90]:
# sigmoid
torch.sigmoid(j)

tensor([[0.9991, 0.9999, 0.8808],
        [0.9991, 0.5000, 0.8808]])

In [93]:
# softmax
torch.softmax(j , dim=0)

tensor([[0.9933, 0.2689, 0.1192],
        [0.0067, 0.7311, 0.8808]])

In [94]:
# relu
torch.relu(j)

tensor([[5., 1., 0.],
        [0., 2., 2.]])

In [95]:
# inplace operations
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1132, 0.4783, 0.4436],
        [0.3847, 0.4521, 0.5569]])
tensor([[0.9952, 0.0015, 0.0813],
        [0.4907, 0.2130, 0.4603]])


In [96]:
m.add_(n) # inplace add

tensor([[1.1084, 0.4798, 0.5249],
        [0.8755, 0.6651, 1.0172]])

In [98]:
m.relu_()

tensor([[1.1084, 0.4798, 0.5249],
        [0.8755, 0.6651, 1.0172]])

In [99]:
# copying a tensor
a = torch.rand(2,3)
a

tensor([[0.1386, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [100]:
b = a

In [101]:
b

tensor([[0.1386, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [103]:
a[0][0] = 0

In [104]:
b

tensor([[0.0000, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [106]:
id(a)
id(b)

131950746348880

In [107]:
b = a.clone()

In [110]:
a[0][0] = 10
a

tensor([[10.0000,  0.0277,  0.5662],
        [ 0.3503,  0.6555,  0.7667]])

In [109]:
b

tensor([[0.0000, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [112]:
id(a)
id(b)

131950746162096

In [113]:
# gpu tensor operations
torch.cuda.is_available()

True

In [114]:
device = torch.device("cuda")

In [115]:
# new tensor in gpu
torch.rand((2,3) , device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [116]:
# move existing to gpu
a

tensor([[10.0000,  0.0277,  0.5662],
        [ 0.3503,  0.6555,  0.7667]])

In [118]:
x = a.to(device)

In [119]:
x + 5

tensor([[15.0000,  5.0277,  5.5662],
        [ 5.3503,  5.6555,  5.7667]], device='cuda:0')

In [121]:
import time

size = 10000

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

# cpu time

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1 , matrix_cpu2)
cpu_time = time.time() - start_time
print(f"time on cpu {cpu_time}")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# gpu time
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1 , matrix_gpu2)
gpu_time = time.time() - start_time
print(f"time on gpu {gpu_time}")

# results
print("cpu / gpu" , cpu_time / gpu_time)

time on cpu 15.701857805252075
time on gpu 0.10968255996704102
cpu / gpu 143.15728781285188


In [122]:
# reshaping tensors

a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [123]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [124]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [125]:
b = torch.rand(2,3,4)
b.permute(2,0,1)
# positions changed ie 2nd will be 0th , 0th will be 1st and 1st will be 2nd

tensor([[[0.4751, 0.7160, 0.0332],
         [0.7324, 0.4399, 0.1828]],

        [[0.9200, 0.2801, 0.6062],
         [0.0059, 0.6325, 0.9434]],

        [[0.0472, 0.6461, 0.9161],
         [0.0328, 0.2586, 0.3875]],

        [[0.5397, 0.9829, 0.5627],
         [0.6305, 0.8932, 0.5627]]])

In [126]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [128]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [129]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

In [130]:
# numpy and pytorch
import numpy as np

In [131]:
a = torch.tensor([1,2,3])

In [132]:
b = a.numpy()

In [133]:
type(b)

numpy.ndarray

In [134]:
torch.from_numpy(np.array([1,2,3]))

tensor([1, 2, 3])