In [3]:
print("lec4")
import torch

lec4


In [6]:
torch.cuda.is_available()
torch.cuda.current_device()
torch.cuda.get_device_name(torch.cuda.current_device())

'Tesla T4'

In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [9]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [10]:
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [11]:
df.shape

(569, 33)

In [12]:
df.drop(columns=['id' , 'Unnamed: 32'], inplace=True)

In [14]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

train test split

In [15]:
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,1:] , df.iloc[:,0] , test_size = 0.2)

scaling

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
X_train

array([[ 0.22798015, -0.61819031,  0.22579031, ...,  0.11414591,
         0.82188174,  0.71268004],
       [-0.00943976, -0.2772684 , -0.07681054, ..., -0.6273718 ,
        -0.44425673, -0.42477674],
       [-1.3224271 , -1.5883305 , -1.31283094, ..., -0.82099857,
        -0.74656964, -0.37132068],
       ...,
       [ 1.66906381,  0.48694581,  1.71157648, ...,  2.24359457,
         4.30498156,  0.98822674],
       [-0.76863135,  1.0406579 , -0.74525422, ..., -0.31189242,
        -1.29593396,  0.15717789],
       [ 3.15707932, -0.43972112,  3.24459401, ...,  2.3491011 ,
         1.26884976,  0.20291865]])

In [18]:
y_train

205    M
298    B
21     B
477    B
160    B
      ..
208    B
105    M
323    M
559    B
352    M
Name: diagnosis, Length: 455, dtype: object

label encoding

In [19]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [20]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,

numpy arr to pytorch tensor

In [21]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [22]:
X_train_tensor.shape

torch.Size([455, 30])

In [23]:
y_train_tensor.shape

torch.Size([455])

define the model

In [46]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1] , dtype=torch.float64 , requires_grad=True) # features
        self.bias = torch.zeros(1 , dtype=torch.float64 , requires_grad=True)
    
    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss 


important params

In [47]:
learning_rate = 0.1
epochs = 25

training pipeline

In [48]:
# create model
model = MySimpleNN(X_train_tensor)
model.weights

tensor([0.3947, 0.8418, 0.2119, 0.3668, 0.0671, 0.9675, 0.5066, 0.7315, 0.5292,
        0.1410, 0.5156, 0.2685, 0.2044, 0.0054, 0.9854, 0.8139, 0.4256, 0.8563,
        0.2789, 0.6652, 0.2655, 0.4932, 0.7073, 0.8253, 0.7731, 0.7701, 0.3794,
        0.8689, 0.4219, 0.9371], dtype=torch.float64, requires_grad=True)

In [49]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [52]:
# in a loop = forward pass -> loss -> backward pass -> param update
for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)

    # loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    # preventing gradient accumulation
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f"epoch : {epoch + 1}, loss : {loss.item()}")

    

epoch : 1, loss : 0.16997377719778972
epoch : 2, loss : 0.16553094296566687
epoch : 3, loss : 0.16125697637428923
epoch : 4, loss : 0.1571498329905998
epoch : 5, loss : 0.15320769977655824
epoch : 6, loss : 0.1494290311356336
epoch : 7, loss : 0.145812564867352
epoch : 8, loss : 0.1423573153295914
epoch : 9, loss : 0.13906254254546843
epoch : 10, loss : 0.13592769661963955
epoch : 11, loss : 0.13295233612884053
epoch : 12, loss : 0.1301360168230081
epoch : 13, loss : 0.12747814421218778
epoch : 14, loss : 0.12497778323880256
epoch : 15, loss : 0.12263342413327685
epoch : 16, loss : 0.12044271802487047
epoch : 17, loss : 0.11840221739126991
epoch : 18, loss : 0.11650717471213004
epoch : 19, loss : 0.11475145722551444
epoch : 20, loss : 0.11312761687821997
epoch : 21, loss : 0.11162711705421209
epoch : 22, loss : 0.11024067692702649
epoch : 23, loss : 0.10895866830260052
epoch : 24, loss : 0.10777149750570414
epoch : 25, loss : 0.10666992227897273


In [53]:
model.weights

tensor([ 0.6340,  0.9846,  0.4177,  0.5812, -0.1405,  0.5891,  0.2669,  0.6915,
         0.2892, -0.5164,  0.5853,  0.1029,  0.2268,  0.1062,  0.6112,  0.1649,
        -0.1543,  0.4221, -0.0556, -0.0976,  0.5136,  0.6669,  0.9172,  1.0410,
         0.6461,  0.5130,  0.1481,  0.8396,  0.3936,  0.4893],
       dtype=torch.float64, requires_grad=True)

In [54]:
model.bias

tensor([-0.1109], dtype=torch.float64, requires_grad=True)

evaluation

In [56]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
print(y_pred)


tensor([0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
        0., 0., 0., 0., 0., 0.])


In [57]:
accuracy = (y_pred == y_test_tensor).float().mean()
print("Accuracy:", accuracy.item())

Accuracy: 0.9561403393745422
