In [1]:
import torch
import torch.nn as nn

In [ ]:
# neural network with one neuron -> sigmoid activation function
class Model(nn.Module):
    def __init__(self , num_features):
        super().__init__()
        self.linear = nn.Linear(in_features=num_features , out_features=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self , features):
        out = self.linear(features) # z = w * x + b
        out = self.sigmoid(out) # y_pred
        return out

    # __call__ is a magic method that allows us to call the forward method

In [3]:
features = torch.rand(10 , 5) # 5 columns = 5 features
model = Model(features.shape[1])
# __call__
model(features)

tensor([[0.4988],
        [0.4895],
        [0.4689],
        [0.4970],
        [0.4860],
        [0.4899],
        [0.5534],
        [0.5424],
        [0.5474],
        [0.5506]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight
model.linear.bias


Parameter containing:
tensor([0.1938], requires_grad=True)

In [7]:
!pip install torchinfo

In [8]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

better nn

5 inputs -> 1 hidden layer with 3 neurons -> 1 output

In [9]:
class Model(nn.Module):
    def __init__(self , num_features):
        super().__init__()
        self.linear1 = nn.Linear(in_features=num_features , out_features=3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(in_features=3 , out_features=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self , features):
        out = self.linear1(features) # z = w * x + b
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out) # y_pred
        return out

In [10]:
features = torch.rand(10 , 5) # 5 columns = 5 features
model = Model(features.shape[1])
# __call__
model(features)

tensor([[0.5603],
        [0.5449],
        [0.5611],
        [0.5682],
        [0.5652],
        [0.5577],
        [0.5533],
        [0.5742],
        [0.5526],
        [0.5643]], grad_fn=<SigmoidBackward0>)

In [14]:
model.linear1.weight
model.linear1.bias
model.linear2.weight
model.linear2.bias

Parameter containing:
tensor([0.1619], requires_grad=True)

In [15]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

sequential container

In [16]:
class Model(nn.Module):
    def __init__(self , num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(in_features=num_features , out_features=3),
            nn.ReLU(),
            nn.Linear(in_features=3 , out_features=1),
            nn.Sigmoid()
        )

    def forward(self , features):
        out = self.network(features)
        return out
        return out

In [17]:
features = torch.rand(10 , 5) # 5 columns = 5 features
model = Model(features.shape[1])
# __call__
model(features)

tensor([[0.5142],
        [0.5281],
        [0.5147],
        [0.5062],
        [0.5183],
        [0.5104],
        [0.5314],
        [0.5160],
        [0.5219],
        [0.5117]], grad_fn=<SigmoidBackward0>)