In [3]:
print("lec5 with improvements using torch.nn and torch.optim")
import torch

lec5 with improvements using torch.nn and torch.optim


In [4]:
torch.cuda.is_available()
torch.cuda.current_device()
torch.cuda.get_device_name(torch.cuda.current_device())

'Tesla T4'

In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [7]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [8]:
df.shape

(569, 33)

In [9]:
df.drop(columns=['id' , 'Unnamed: 32'], inplace=True)

In [10]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

train test split

In [11]:
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,1:] , df.iloc[:,0] , test_size = 0.2)

scaling

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train

array([[-0.82451942,  0.47660594, -0.85102979, ..., -1.1103316 ,
         0.09955834, -0.72039873],
       [ 0.44273323,  0.00597178,  0.34930901, ..., -0.46101386,
        -0.37711958, -0.8780388 ],
       [ 1.25149672,  0.59252569,  1.183968  , ...,  0.33456035,
         0.31593432, -0.45927386],
       ...,
       [-0.79319407, -0.89356544, -0.75062279, ..., -0.5061096 ,
        -1.23286219,  1.05278394],
       [-0.73054338, -1.10453938, -0.72541774, ..., -0.63423635,
         0.04261729,  0.38254556],
       [ 0.60220772, -0.76141693,  0.60962345, ...,  0.13955173,
         0.38751735,  0.2645836 ]])

In [14]:
y_train

419    B
263    M
134    M
431    B
202    M
      ..
297    M
437    B
388    B
478    B
375    B
Name: diagnosis, Length: 455, dtype: object

label encoding

In [15]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [16]:
y_train

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

numpy arr to pytorch tensor

In [40]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [41]:
X_train_tensor.shape

torch.Size([455, 30])

In [42]:
y_train_tensor.shape

torch.Size([455])

define the model

In [59]:
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self , num_features):
        super().__init__()
        self.linear = nn.Linear(num_features , 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    
    


important params

In [60]:
learning_rate = 0.1
epochs = 25

In [61]:
loss_function = nn.BCELoss()

In [62]:
type(loss_function)

torch.nn.modules.loss.BCELoss

training pipeline

In [63]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [64]:
# in a loop = forward pass -> loss -> backward pass -> param update
for epoch in range(epochs):
    # forward pass
    y_pred = model(X_train_tensor)
    # print(y_pred)

    # loss calculation
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    optimizer.zero_grad()
    
    # backward pass
    loss.backward()

    # parameter update
    optimizer.step()


    # print loss in each epoch
    print(f"epoch : {epoch + 1}, loss : {loss.item()}")


    

epoch : 1, loss : 0.7111859321594238
epoch : 2, loss : 0.5310214757919312
epoch : 3, loss : 0.43887537717819214
epoch : 4, loss : 0.3837623596191406
epoch : 5, loss : 0.34641751646995544
epoch : 6, loss : 0.3190650939941406
epoch : 7, loss : 0.2979500889778137
epoch : 8, loss : 0.2810222804546356
epoch : 9, loss : 0.26706060767173767
epoch : 10, loss : 0.2552889585494995
epoch : 11, loss : 0.24518828094005585
epoch : 12, loss : 0.23639686405658722
epoch : 13, loss : 0.22865401208400726
epoch : 14, loss : 0.2217666059732437
epoch : 15, loss : 0.2155880630016327
epoch : 16, loss : 0.21000468730926514
epoch : 17, loss : 0.204926997423172
epoch : 18, loss : 0.2002832293510437
epoch : 19, loss : 0.1960151493549347
epoch : 20, loss : 0.1920749694108963
epoch : 21, loss : 0.18842290341854095
epoch : 22, loss : 0.18502569198608398
epoch : 23, loss : 0.18185509741306305
epoch : 24, loss : 0.17888721823692322
epoch : 25, loss : 0.17610134184360504


In [65]:
model.linear.bias
model.linear.weight

Parameter containing:
tensor([[ 0.2594,  0.0840,  0.4013,  0.2392,  0.1124,  0.0656,  0.0619,  0.4128,
         -0.0047, -0.0242,  0.0502, -0.1362,  0.0905,  0.2838,  0.0844, -0.1160,
         -0.0275, -0.0464,  0.0536,  0.0834,  0.3759,  0.3383,  0.2220,  0.1543,
          0.1132,  0.2397,  0.2804,  0.1000,  0.1773,  0.1059]],
       requires_grad=True)

evaluation

In [66]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
print(y_pred)


tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
      

In [67]:
accuracy = (y_pred == y_test_tensor).float().mean()
print("Accuracy:", accuracy.item())

Accuracy: 0.5646352767944336
