In [40]:
print("lec6 with improvements using dataset and dataloader classes - mini batch gradient descent")
import torch

lec6 with improvements using dataset and dataloader classes - mini batch gradient descent


In [41]:
torch.cuda.is_available()
torch.cuda.current_device()
torch.cuda.get_device_name(torch.cuda.current_device())

'Tesla T4'

In [42]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [43]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [44]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [45]:
df.shape

(569, 33)

In [46]:
df.drop(columns=['id' , 'Unnamed: 32'], inplace=True)

In [47]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

train test split

In [48]:
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,1:] , df.iloc[:,0] , test_size = 0.2)

scaling

In [49]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [50]:
X_train

array([[ 1.57339446, -0.08926408,  1.58452858, ...,  1.27928288,
         0.10187314,  0.85198429],
       [-0.51887384,  1.80612575, -0.45438449, ...,  0.48668454,
         0.49112322,  2.01992352],
       [ 0.40940653,  3.40149157,  0.49654601, ...,  1.33100715,
         0.95916887,  2.01441697],
       ...,
       [-0.89134998, -1.02743442, -0.8617454 , ..., -0.09749543,
         0.62665159,  0.3844782 ],
       [-0.77786116,  0.40363252, -0.76391131, ..., -0.80079335,
        -0.22276458,  0.25837821],
       [-0.19295722,  2.12758006, -0.25449932, ..., -0.8534304 ,
        -0.32992655, -0.72729422]])

In [51]:
y_train

300    M
193    M
259    M
224    B
103    B
      ..
23     M
430    M
342    B
80     B
377    B
Name: diagnosis, Length: 455, dtype: object

label encoding

In [52]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [53]:
y_train

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,

numpy arr to pytorch tensor

In [54]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [55]:
X_train_tensor.shape

torch.Size([455, 30])

In [56]:
y_train_tensor.shape

torch.Size([455])

In [57]:
from torch.utils.data import DataLoader , Dataset

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

define the model

In [58]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)

test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [59]:
train_dataset[10]

(tensor([-0.6091, -0.3202, -0.6678, -0.6065, -1.3759, -1.2218, -1.0734, -1.1041,
         -1.5414, -0.2905, -0.6548, -0.5462, -0.7305, -0.5440, -0.7391, -1.0124,
         -0.9602, -1.2498, -0.6922, -0.7290, -0.6730, -0.5707, -0.7372, -0.6364,
         -1.3692, -1.1411, -1.2516, -1.3075, -1.1541, -0.7405]),
 tensor(0.))

In [60]:
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False)

In [61]:
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self , num_features):
        super().__init__()
        self.linear = nn.Linear(num_features , 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    
    


important params

In [62]:
learning_rate = 0.1
epochs = 25

In [63]:
loss_function = nn.BCELoss()

In [64]:
type(loss_function)

torch.nn.modules.loss.BCELoss

training pipeline

In [65]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [66]:
# in a loop = forward pass -> loss -> backward pass -> param update
for epoch in range(epochs):
    for batch_features , batch_labels in train_loader:
        # forward pass
        y_pred = model(batch_features)
        # print(y_pred)

        # loss calculation
        loss = loss_function(y_pred, batch_labels.view(-1, 1))

        optimizer.zero_grad()
        
        # backward pass
        loss.backward()

        # parameter update
        optimizer.step()


        # print loss in each epoch
        print(f"epoch : {epoch + 1}, loss : {loss.item()}")


    

epoch : 1, loss : 0.7574967741966248
epoch : 1, loss : 0.6248430013656616
epoch : 1, loss : 0.5239499807357788
epoch : 1, loss : 0.34852203726768494
epoch : 1, loss : 0.33132264018058777
epoch : 1, loss : 0.32851460576057434
epoch : 1, loss : 0.2759499251842499
epoch : 1, loss : 0.2863367795944214
epoch : 1, loss : 0.2816965878009796
epoch : 1, loss : 0.3272751271724701
epoch : 1, loss : 0.2962522506713867
epoch : 1, loss : 0.3081722557544708
epoch : 1, loss : 0.20981059968471527
epoch : 1, loss : 0.253897488117218
epoch : 1, loss : 0.3001227378845215
epoch : 2, loss : 0.1820162832736969
epoch : 2, loss : 0.16125160455703735
epoch : 2, loss : 0.26158958673477173
epoch : 2, loss : 0.19515730440616608
epoch : 2, loss : 0.19083841145038605
epoch : 2, loss : 0.1375945657491684
epoch : 2, loss : 0.13865524530410767
epoch : 2, loss : 0.17172545194625854
epoch : 2, loss : 0.20326876640319824
epoch : 2, loss : 0.11233308911323547
epoch : 2, loss : 0.20302417874336243
epoch : 2, loss : 0.216043

In [67]:
model.linear.bias
model.linear.weight

Parameter containing:
tensor([[ 0.5047,  0.5881,  0.5068,  0.6241,  0.1061,  0.1275,  0.3031,  0.5476,
         -0.0200, -0.2174,  0.4717, -0.0512,  0.3354,  0.4625,  0.0219, -0.4311,
         -0.1289,  0.1176, -0.0303, -0.2561,  0.5976,  0.6224,  0.7046,  0.7563,
          0.6150,  0.0832,  0.4992,  0.7249,  0.5449,  0.1419]],
       requires_grad=True)

evaluation

In [68]:
model.eval()
accuracy_list = []
with torch.no_grad():
    for batch_features , batch_labels in test_loader:
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"accuracy: {overall_accuracy:.4f}")

accuracy: 0.9766
